'''
Created on Apr 6, 2011

@author: aaron
'''

import general_utilities

def solve():
    '''
    Each new term in the Fibonacci sequence is generated by adding
    the previous two terms. By starting with 1 and 2, the first 10
    terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values
    do not exceed four million, find the sum of the even-valued terms.
    '''
    total = 0
    for i, val in enumerate(general_utilities.naive_fibonacci()):
        if val > 4000000:
            break;
        # every 3rd term in the sequence is even, so only count those
        if (i+1) % 3 == 0:
            total += val
    return total
        
if __name__ == '__main__':
    print(solve())